
url: http://srcmvn.com
title: Source Maven
subtitle: Code Partition for Beau Simensen
author: Beau Simensen

octopress_project_path: /home/altern8/workspaces/srcmvn.com

#source: /home/altern8/workspaces/srcmvn.com/source
#blog_index_dir: /home/altern8/workspaces/srcmvn.com/source
#actual_blog_root: /home/altern8/workspaces/srcmvn.com
#jekyll_config: /home/altern8/workspaces/srcmvn.com/source/_config.yml

default_asides: [asides/recent_posts.html]

github_user: simensen
github_repo_count: 5
github_skip_forks: false

twitter_user: srcmvn
twitter_tweet_count: 5

googleplus_user: 114524966156217554571
googleplus_hidden: true

disqus_short_name: srcmvn

google_analytics_tracking_id: UA-12685022-2

deploy_config: rsync

hub_url: http://dflydev.superfeedr.com/

#ssh_user: srcmvn@www000.farm000.dflydev.com
#ssh_port: 4668
#document_root: ~/public_html/
#deploy_default: rsync
